### PR TITLE
add onlyautocomplete flag

### PR DESCRIPTION
**Pull request by urkle**
- this will only allow tags to be added IF they were added via
 autocomplete

### CODE REVIEW

**Comment by urkle** [comment]
is this PR being manually pulled in? or rejected?  do I need to rework how it's done?  or rebase it off of master?   some more information on why it was closed would be extremely helpful.

**Comment by lucknerjb** [comment]
@urkle A number of issues and PRs were closed either because they were no longer relevant or are going to be merged into v2 which comes out in a few weeks. No new features are being added to the current version.

The change that you propose makes sense and will be added in v2 but might end up being a config option OR be left to the user to implement via the new callback methods.

Sorry I didn't give you any feedback before closing the PR, I figured it was forgotten about since it's been nearly 3 years.

**Comment by urkle** [comment]
nope.. we are still using the modified version in our apps..   once v2 is released I'll update one of the applications to it and get this functionality working OR send a new PR to get it working.

**Comment by lucknerjb** [comment]
I get that you want to keep your code the way it is as much as possible but not every feature can make it into the plugin's base code. I'm thinking it will be possible as a callback function where you check the tag source and say yay or nay for the initial release of v2 and if there are enough requests for it, it will be added as a config option.

**Pull request closed without merging**
