### PR TITLE
change delimiter from string to array

### PR DESCRIPTION
**Pull request by qq286735628**
change delimiter from string to array

```javascript
$(selector).tagsInput({
    'delimiter': [',',';']
});
```

### CODE REVIEW

**Comment by slaporte** [comment]
I like it!

**Comment by qq286735628** [comment]
no one to update this repository？

**Comment by lucknerjb** [comment]
Hey guys, I've come on as a maintainer but things got a little busy in the past week or so. I'll take a look at the PR and merge it if it all looks good

**Comment by slaporte** [comment]
Awesome, thanks! I'm using a slightly forked version on listen.hatnote.com for the hashtag settings. If you are actively maintaining, I can send you a few pulls.

**Comment by lucknerjb** [comment]
Yup, I'm actively maintaining. At this point, I hope to be able to do some work and merge some PRs every second day or so. If you've got some stuff you want to submit, fire away!

**Comment by slaporte** [comment]
Nice. :thumbsup:

**Comment by feizhou2015** [comment]
not work for jquery 1.11,  tags was saved such as "123,;".
'delimiter': [','] works well.

**Pull request merged**
